import { IDemoBattle } from '../../../../common/resources/interfaces/game.interface';

export const demoBattles: IDemoBattle[] = [
  {
    player: {
      name: 'Player',
      head: { name: 'gun_1', path: 'assets/images/tanks/gun_1.png' },
      body: { name: 'T_1', path: 'assets/images/tanks/T_1.png' },
      team: 'red',
      level: 5,
      kills: 23,
      deaths: 15,
      date: Date.now(),
    },
    bots: [
      {
        name: 'ally1',
        head: { name: 'gun_1', path: 'assets/images/tanks/gun_1.png' },
        body: { name: 'T_1', path: 'assets/images/tanks/T_1.png' },
        team: 'red',
        level: 5,
        kills: 23,
        deaths: 15,
        date: Date.now(),
      },
      {
        name: 'ally2',
        head: { name: 'gun_1', path: 'assets/images/tanks/gun_1.png' },
        body: { name: 'T_1', path: 'assets/images/tanks/T_1.png' },
        team: 'red',
        level: 5,
        kills: 23,
        deaths: 15,
        date: Date.now(),
      },
      {
        name: 'ally3',
        head: { name: 'gun_1', path: 'assets/images/tanks/gun_1.png' },
        body: { name: 'T_1', path: 'assets/images/tanks/T_1.png' },
        team: 'red',
        level: 5,
        kills: 23,
        deaths: 15,
        date: Date.now(),
      },
      {
        name: 'enemy1',
        head: { name: 'gun_1', path: 'assets/images/tanks/gun_1.png' },
        body: { name: 'T_1', path: 'assets/images/tanks/T_1.png' },
        team: 'red',
        level: 5,
        kills: 23,
        deaths: 15,
        date: Date.now(),
      },
      {
        name: 'enemy2',
        head: { name: 'gun_1', path: 'assets/images/tanks/gun_1.png' },
        body: { name: 'T_1', path: 'assets/images/tanks/T_1.png' },
        team: 'red',
        level: 5,
        kills: 23,
        deaths: 15,
        date: Date.now(),
      },
      {
        name: 'enemy3',
        head: { name: 'gun_1', path: 'assets/images/tanks/gun_1.png' },
        body: { name: 'T_1', path: 'assets/images/tanks/T_1.png' },
        team: 'red',
        level: 5,
        kills: 23,
        deaths: 15,
        date: Date.now(),
      },
      {
        name: 'enemy4dcdcdcdcdc',
        head: { name: 'gun_1', path: 'assets/images/tanks/gun_1.png' },
        body: { name: 'T_1', path: 'assets/images/tanks/T_1.png' },
        team: 'red',
        level: 5,
        kills: 23,
        deaths: 15,
        date: Date.now(),
      },
    ],
  },
];
